// Datos de ejemplo que simulan la estructura real de los CSV
export const sampleData = {
  general: [
    {
      CUIT: "27176350259",
      Razon_Social: "VON BRUDERSDORFF CLAUDIA",
      Ha_Totales: "2754.0",
      Ha_Agricolas_Totales: "491.0",
      Ha_Agricolas_Propias: "0.0",
      Ha_Agricolas_Alquiladas: "491.0",
      Ha_No_Agricolas_Totales: "2263.0",
      Ha_No_Agricolas_Propias: "1419.0",
      Ha_No_Agricolas_Alquiladas: "844.0",
      Pct_Agricolas: "17.83",
      Pct_No_Agricolas: "82.17",
      Pct_Agricolas_Propias: "0.0",
      Pct_Agricolas_Alquiladas: "100.0",
      Pct_No_Agricolas_Propias: "62.7",
      Pct_No_Agricolas_Alquiladas: "37.3",
      Cabezas_Totales: "12718",
      Stock_Cria_Cabezas: "2005",
      Valor_Stock_Total: "4266808.0",
      Valor_Stock_Cria: "632479.0",
      Score_Nosis: "843.0",
      Endeudamiento: "70.58823529",
      GeoJSON_Propios: "geojson_propios_27176350259.geojson",
      GeoJSON_Alquilados: "geojson_alquilados_27176350259.geojson",
      GeoJSON_Total:
        "Propios: geojson_propios_27176350259.geojson | Alquilados: geojson_alquilados_27176350259.geojson",
    },
    {
      CUIT: "20123456789",
      Razon_Social: "ESTANCIA LA ESPERANZA SA",
      Ha_Totales: "1850.0",
      Ha_Agricolas_Totales: "650.0",
      Ha_Agricolas_Propias: "400.0",
      Ha_Agricolas_Alquiladas: "250.0",
      Ha_No_Agricolas_Totales: "1200.0",
      Ha_No_Agricolas_Propias: "1200.0",
      Ha_No_Agricolas_Alquiladas: "0.0",
      Pct_Agricolas: "35.14",
      Pct_No_Agricolas: "64.86",
      Pct_Agricolas_Propias: "61.54",
      Pct_Agricolas_Alquiladas: "38.46",
      Pct_No_Agricolas_Propias: "100.0",
      Pct_No_Agricolas_Alquiladas: "0.0",
      Cabezas_Totales: "8500",
      Stock_Cria_Cabezas: "1200",
      Valor_Stock_Total: "2850000.0",
      Valor_Stock_Cria: "380000.0",
      Score_Nosis: "756.0",
      Endeudamiento: "35.2",
      GeoJSON_Propios: "geojson_propios_20123456789.geojson",
      GeoJSON_Alquilados: "geojson_alquilados_20123456789.geojson",
      GeoJSON_Total:
        "Propios: geojson_propios_20123456789.geojson | Alquilados: geojson_alquilados_20123456789.geojson",
    },
  ],
  crediticio: [
    {
      CUIT: "27176350259",
      Tipo_Dato: "Recomendacion_Credito",
      Categoria: "MONTO_CONSERVADOR",
      Subcategoria: "Recomendado_80%",
      Detalle: "Margen_Seguridad_20%",
      Valor_Numerico: "133013.16674510133",
      Valor_Texto: "$133,013",
      Unidad: "usd",
      Departamento: "TODOS",
      Provincia: "TODAS",
    },
    {
      CUIT: "27176350259",
      Tipo_Dato: "Recomendacion_Credito",
      Categoria: "MONTO_OPTIMISTA",
      Subcategoria: "Recomendado_90%",
      Detalle: "Margen_Seguridad_10%",
      Valor_Numerico: "149640.0",
      Valor_Texto: "$149,640",
      Unidad: "usd",
      Departamento: "TODOS",
      Provincia: "TODAS",
    },
    {
      CUIT: "27176350259",
      Tipo_Dato: "Recomendacion_Credito",
      Categoria: "MONTO_MAXIMO",
      Subcategoria: "Recomendado_100%",
      Detalle: "Sin_Margen_Seguridad",
      Valor_Numerico: "166266.0",
      Valor_Texto: "$166,266",
      Unidad: "usd",
      Departamento: "TODOS",
      Provincia: "TODAS",
    },
    {
      CUIT: "20123456789",
      Tipo_Dato: "Recomendacion_Credito",
      Categoria: "MONTO_CONSERVADOR",
      Subcategoria: "Recomendado_80%",
      Detalle: "Margen_Seguridad_20%",
      Valor_Numerico: "95000.0",
      Valor_Texto: "$95,000",
      Unidad: "usd",
      Departamento: "TODOS",
      Provincia: "TODAS",
    },
  ],
  agricultura: [
    {
      CUIT: "27176350259",
      Tipo_Analisis: "Detalle_Cultivo_Tenencia",
      Tenencia: "Propios",
      Cultivo: "soja",
      Departamento: "TODOS",
      Provincia: "TODAS",
      Ha_Superficie: "200.0",
      Rendimiento_10_Anos_Tn_Ha: "2.8",
      Rendimiento_5_Anos_Tn_Ha: "3.1",
      KM_Ponderados_Cultivos: "45.2",
      KM_Ponderados_Superficie: "284.7",
      Costo_Flete_Ha: "125.0",
      Ingreso_Bruto_Total: "168000.0",
      Ingreso_Neto_Total: "89600.0",
    },
    {
      CUIT: "27176350259",
      Tipo_Analisis: "Detalle_Cultivo_Tenencia",
      Tenencia: "Alquiladas",
      Cultivo: "maiz",
      Departamento: "TODOS",
      Provincia: "TODAS",
      Ha_Superficie: "291.0",
      Rendimiento_10_Anos_Tn_Ha: "8.5",
      Rendimiento_5_Anos_Tn_Ha: "9.2",
      KM_Ponderados_Cultivos: "52.1",
      KM_Ponderados_Superficie: "284.7",
      Costo_Flete_Ha: "98.0",
      Ingreso_Bruto_Total: "245820.0",
      Ingreso_Neto_Total: "147492.0",
    },
  ],
  ganaderia: [
    {
      CUIT: "27176350259",
      Tipo_Dato: "Carga_Animal",
      Categoria: "EFICIENCIA",
      Subcategoria: "Cabezas_Por_Hectarea",
      Detalle: "Ratio",
      Departamento: "TODOS",
      Provincia: "TODAS",
      Valor_Numerico: "5.619973486522316",
      Valor_Texto: "5.62 cab/ha",
      Unidad: "cabezas_por_hectarea",
    },
    {
      CUIT: "27176350259",
      Tipo_Dato: "Productividad",
      Categoria: "RENDIMIENTO",
      Subcategoria: "Kg_Carne_Por_Ha",
      Detalle: "Produccion_Anual",
      Departamento: "TODOS",
      Provincia: "TODAS",
      Valor_Numerico: "285.5",
      Valor_Texto: "285.5 kg/ha",
      Unidad: "kg_por_hectarea",
    },
  ],
  activos: [
    {
      CUIT: "27176350259",
      Tipo_Dato: "Hectareas_Valuadas",
      Categoria: "TOTAL",
      Subcategoria: "Superficie_Con_Precio",
      Detalle: "Hectareas",
      Departamento: "TODOS",
      Provincia: "TODAS",
      Valor_Numerico: "1433.148751959501",
      Valor_Texto: "1433.1 ha",
      Unidad: "hectareas",
    },
    {
      CUIT: "27176350259",
      Tipo_Dato: "Valor_Total",
      Categoria: "ACTIVOS",
      Subcategoria: "Valor_Tierras",
      Detalle: "USD",
      Departamento: "TODOS",
      Provincia: "TODAS",
      Valor_Numerico: "5732595.0",
      Valor_Texto: "$5,732,595",
      Unidad: "usd",
    },
  ],
  rotacion: [
    {
      CUIT: "27176350259",
      Tipo_Rotacion: "Total_Departamento",
      Tenencia: "AMBAS",
      Provincia: "Buenos Aires",
      Departamento: "Pila",
      Cultivo: "TODOS",
      Ha_Promedio_Anual: "17.2",
      Fuente_Archivo: "CALCULADO",
    },
  ],
}
